version: '3'
services:
  db:
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:delegated
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "password"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/kawaii
    ports:
      - "13000:3000"
    depends_on:
      - db
    env_file: .env
    stdin_open: true
    tty: true

  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     - .:/kawaii
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db

